Add FreeBSD CI target
hughsie/libjcat pull request #52
Opened 2021-05-21 13:42 UTC by hughsie

2021-05-21 14:07 UTC, hughsie commented
@Asiderr this one looks okay too?

2021-05-21 14:43 UTC, Asiderr requested changes
Does not work on FreeBSD 12.2. Needed change https://github.com/hughsie/libjcat/blob/master/libjcat/meson.build#L142:
```
+  python_interpreter = python.find_installation(
-  python_interpreter = python.find_installation('python3',
```

2021-05-21 14:45 UTC, hughsie commented
Ahh, good catch, thanks.

2021-05-21 14:51 UTC, Asiderr approved these changes

2021-05-21 14:52 UTC, merged

2021-10-19 01:09 UTC, jtojnar commented
> Does not work on FreeBSD 12.2. Needed change [`master`/libjcat/meson.build#L142](https://github.com/hughsie/libjcat/blob/master/libjcat/meson.build#L142):
> 
> ```
> +  python_interpreter = python.find_installation(
> -  python_interpreter = python.find_installation('python3',
> ```

That is incorrect – the change will cause Meson to use its own Python installation (see [docs](https://mesonbuild.com/Python-module.html#find_installation)), which may be different from the one on `PATH` and have different set of modules available. For example, on Nix Meson’s python does not have any modules available so the configuration will fail, even though python with correct modules is available on `PATH`.

@Asiderr Could you provide the error message you get? Maybe we need to fix Meson to find Python correctly on BSD: https://github.com/mesonbuild/meson/blob/492cc9bf95d573e037155b588dc5110ded4d9a35/mesonbuild/modules/python.py#L659 

Edit: We actually have an issue about that https://github.com/mesonbuild/meson/issues/4608 so input from someone with BSD background would be appreciated.